### PR TITLE
Add Vaibhav Tripathi

### PR DESCRIPTION
**Pull request by vaibhavtripathi1209**

### CODE REVIEW

**Comment by vaibhavtripathi1209** [comment]
please approved it

**Comment by devabhixda** [comment]
Already merged

**Comment by vaibhavtripathi1209** [comment]
sir, please add "hacktoberfest" label on this repository so that it participates in "hacktoberfest"

**Comment by devabhixda** [comment]
This is just a demo repo and does not fit into hacktoberfest criteria

**Pull request merged**
